# Generated by Django 5.1.2 on 2026-09-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_taskhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
