# Generated by Django 5.1.2 on 2026-09-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_taskhistory_user_delete_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
