# Generated by Django 5.1.2 on 2026-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'انجام نشده'), ('IN_PROGRESS', 'درحال انجام'), ('DONE', 'پایان')], default='TODO', max_length=15)),
                ('started_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
