# Generated by Django 5.1.2 on 2026-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_date',
            field=models.DateTimeField(),
        ),
    ]
