# Generated by Django 5.1.2 on 2026-10-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
    ]
