# Generated by Django 5.1.2 on 2026-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="workspace_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
